version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-Web
    container_name: ${IMAGE_NAME}
    ports:
      - "80:5000"
    environment:
      - IN_DOCKER=true
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
    depends_on:
      - db
    env_file:
      - ./config.env

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./config.env

volumes:
  mysql_data:
