

localize_info = {
	"en": {
		"TID_USER_INFO_NEED": "Email, username and password are required",
		"TID_USER_EMAIL_EXIST": "Email already exists",
		"TID_USER_SEND_DONE": "Verification code sent to email",
		"TID_USER_REGISTERED_SUCCESS": "User registered successfully",
		"TID_USER_INVALID_CODE": "Invalid verification code",
		"TID_USER_LOGIN_INVALID": "Invalid credentials",
		"TID_USER_BASE_REQUIRED": "User ID, username, or email is required",
		"TID_USER_NOT_FOUND": "User not found",
		"TID_USER_UP_NEED": "User ID and new username are required",
		"TID_USER_UP_OTHER": "You can only update your own account",
		"TID_USER_UP_SUCCESS": "User updated successfully",
		"TID_USER_ID_NEED": "User ID is required",
		"TID_USER_DELETE_SUCCESS": "User deleted successfully",
		"TID_INIT_PROJECT_CREAT_TABLE_SUCCESS": "All tables created successfully",
		"TID_INIT_PROJECT_MIGRATIONS_SUCCESS": "Migrations run successfully",
		"TID_PAGE_NOT_FOUND": "Page not found",
		"TID_PAGE_SERVER_ERROR": "Internal server error",
		"TID_AUTH_NO_TOKEN": "Token is missing",
		"TID_AUTH_EXPIRED_TOKEN": "Token has expired",
		"TID_AUTH_INVALID_TOKEN": "Invalid token",
		"TID_AUTH_NO_PERMISSION": "You do not have permission to perform this action",
	},
	"ch": {
		"TID_USER_INFO_NEED": "邮箱，用户名和密码是必填项",
		"TID_EMAIL_EXIST": "邮箱已存在",
		"TID_USER_SEND_DONE": "验证码发送至邮箱",
		"TID_USER_REGISTERED_SUCCESS": "用户注册成功",
		"TID_USER_INVALID_CODE": "无效的验证码",
		"TID_USER_LOGIN_INVALID": "密码错误",
		"TID_USER_BASE_REQUIRED": "用户 ID, 用户名或邮箱是必填项",
		"TID_USER_NOT_FOUND": "用户不存在",
		"TID_USER_UP_NEED": "用户 ID 和新用户名是必填项",
		"TID_USER_UP_OTHER": "您只能更新自己的账户",
		"TID_USER_UP_SUCCESS": "用户更新成功",
		"TID_USER_ID_NEED": "用户 ID 是必填项",
		"TID_USER_DELETE_SUCCESS": "用户删除成功",
		"TID_INIT_PROJECT_CREAT_TABLE_SUCCESS": "所有表创建成功",
		"TID_INIT_PROJECT_MIGRATIONS_SUCCESS": "迁移成功",
		"TID_PAGE_NOT_FOUND": "页面不存在",
		"TID_PAGE_SERVER_ERROR": "内部服务器错误",
		"TID_AUTH_NO_TOKEN": "请您先登录",
		"TID_AUTH_EXPIRED_TOKEN": "登录已过期, 请重新登录",
		"TID_AUTH_INVALID_TOKEN": "非法操作, 停下",
		"TID_AUTH_NO_PERMISSION": "您没有权限执行此操作",
	}
}
