name: Deploy App

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        id: setup_env
        run: |
          source <(grep -E 'IMAGE_NAME|SERVER_IP|USER_NAME' config.ini | sed 's/^\(.*\)=\(.*\)$/export \1="\2"/')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "SERVER_IP=$SERVER_IP" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV

      - name: Deploy code to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./
          target: /tmp/app

      - name: Run deploy script
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x /tmp/deploy.sh
            /tmp/deploy.sh ${{ env.IMAGE_NAME }}
