name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Save Docker image
        run: docker save flask-app | gzip > flask-app.tar.gz

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -T -o StrictHostKeyChecking=no flask-app.tar.gz root@123.207.50.78:/tmp/flask-app.tar.gz
          ssh -i private_key.pem -T -o StrictHostKeyChecking=no root@123.207.50.78 << EOF
            docker load -i /tmp/flask-app.tar.gz
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 80:5000 flask-app
          EOF

          # Clean up
          rm private_key.pem
