name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: docker/cache-action@v2
        with:
          path: |
            /tmp/.buildx-cache

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Save Docker image
        run: docker save flask-app | gzip > flask-app.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: flask-app-image
          path: flask-app.tar.gz

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -i /path/to/private/key flask-app.tar.gz username@your.server.ip.address:/home/username/
          ssh -i /path/to/private/key username@your.server.ip.address << EOF
            gunzip /home/username/flask-app.tar.gz
            docker load -i /home/username/flask-app.tar
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 80:80 flask-app
          EOF
