name: Deploy App

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        uses: falti/dotenv-action@v1.1.4
        id: dotenv
        with:
          path: project/config.env
          keys-case: bypass
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install React dependencies
        run: |
          cd project/easy_react
          npm install

      - name: Build React app
        run: |
          cd project/easy_react
          npm run build
          rm -rf ./node_modules

      - name: Deploy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.dotenv.outputs.SERVER_IP }}
          username: ${{ steps.dotenv.outputs.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: project
          target: /tmp

      - name: Run deploy script
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ steps.dotenv.outputs.SERVER_IP }}
          username: ${{ steps.dotenv.outputs.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x /tmp/project/deploy.sh
            /tmp/project/deploy.sh
