name: Docker Build and Push

on:
    push:
        tags:
            - "docker*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Pull MySQL Docker image
              run: |
                  docker pull mysql:8.0
                  docker pull python:3.11-slim-buster

            - name: Save MySQL Docker image
              run: |
                  docker save mysql:8.0 -o mysql_8.0.tar
                  docker save python:3.11-slim-buster -o python_3.11.tar
                  chmod 644 mysql_8.0.tar python_3.11.tar

            - name: Set up environment variables
              uses: falti/dotenv-action@v1.1.4
              id: dotenv
              with:
                  path: project/.env
                  keys-case: bypass

            - name: Deploy project to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ steps.dotenv.outputs.SERVER_IP }}
                  username: ${{ steps.dotenv.outputs.USER_NAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  source: mysql_8.0.tar, python_3.11.tar, project/dockerDeploy.sh
                  target: /tmp

            - name: Run deploy script
              uses: appleboy/ssh-action@v0.1.0
              with:
                  host: ${{ steps.dotenv.outputs.SERVER_IP }}
                  username: ${{ steps.dotenv.outputs.USER_NAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      chmod +x /tmp/dockerDeploy.sh
                      /tmp/dockerDeploy.sh
